name: Run Benchmarks

on:
    workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-latest-16-cores"
          - "ubuntu-latest-32-cores"
          - "ubuntu-latest-64-cores"
        python-version: ["3.10"]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --python ${{ matrix.python-version }} --extra lgb --locked

      - name: Benchmark
        run: |
          uv run pytest -k "test_benchmark" -vv \
            --benchmark-name=short \
            --benchmark-group-by=param \
            --benchmark-min-rounds=3 \
            --benchmark-columns=min,max,mean,median,stddev,rounds,iterations \
            --benchmark-json=docs/benchmarks/${{ matrix.os }}.json

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update ${{ matrix.os }} benchmark"
          file_pattern: docs/benchmarks/${{ matrix.os }}.json
