# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Quickstart

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'functime/**'
      - 'pyproject.toml'
      - 'docs/code/quickstart.py'
      - '.github/workflows/quickstart.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  quickstart:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Rust
        run: rustup show
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Create virtual environment
        run: python3 -m venv venv
      - name: Install functime
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install maturin
          maturin develop
      - name: Install extra dependencies
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade pip
      - name: Run Quickstart
        run: |
          source venv/bin/activate
          python docs/code/quickstart.py
          python docs/code/feature_engineering.py
