name: Quickstart

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "functime/**"
      - "pyproject.toml"
      - "docs/code/quickstart.py"
      - ".github/workflows/quickstart.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  quickstart:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        run: rustup show

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install functime
        env:
          RUSTFLAGS: -C debuginfo=0  # Do not produce debug symbols to keep memory usage down
        run: |
          uv sync --python ${{ matrix.python-version }} --locked
          uv run --with "maturin>=1.5" -- maturin develop

      - name: Run Quickstart
        run: |
          uv run python docs/code/quickstart.py
          uv run python docs/code/feature_engineering.py
